apiVersion: v2
name: stalwart
description: Stalwart mail server (SMTP/IMAP/JMAP/webadmin) - chart maison pour georgeop.us
type: application
version: 0.2.0
appVersion: "0.16.16"
sources:
  - https://github.com/stalwartlabs/stalwart
