apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: stalwart-db
  namespace: stalwart
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4   # ta version habituelle
  bootstrap:
    initdb:
      database: stalwart
      owner: stalwart
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"    # le mail est plus gourmand qu'Authelia
  storage:
    size: 20Gi                   # les mails vivront ICI désormais
    storageClass: local-path
  resources:
    requests: {cpu: 100m, memory: 256Mi}
    limits: {memory: 1Gi}
  # backup: barmanObjectStore -> PRIORITAIRE pour celui-ci, c'est du mail
